# -*- coding: utf-8 -*-
"""ElectricityDemandPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRxbBVRtG3QjFMluAhhQPm9pUtfd8X16
"""

# Commented out IPython magic to ensure Python compatibility.
# import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import random

from google.colab import files
files.upload()

data = pd.read_csv("ElectricityDemandDataset.csv")

data

# Check some basic information about the dataset
data.info()

# Convert the 'Timestamp' column datatype to datetime format
data['Timestamp'] = pd.to_datetime(data['Timestamp'])

data.info()

# Set the 'Timestamp' column as DataFrame's index
data = data.set_index("Timestamp")

data

# Using Describe function to check the summary statistics
data[["Temperature","Humidity","Demand"]].describe()

# Check for Missing Values

data.isnull().sum()

# To show the records that contain Any null values

data[data.isna().any(axis=1)]

# To show the records that contain All null values

data[data.isna().all(axis=1)]

# Drop those rows that contain All missing values

data = data.dropna(how = 'all')
data

# To show the records that contain All null values

data[data.isna().all(axis=1)]

# Check for Missing Values

data.isnull().sum()

"""Backward Fill - bfill

Forward Fill - ffill
"""

# Applying 'ffill' method on columns

data[['hour', 'dayofweek', 'month', 'year', 'dayofyear']] = data[['hour', 'dayofweek', 'month', 'year', 'dayofyear']].ffill()

"""Mantık: Eksik bir değeri, kendisinden bir önceki geçerli değerle doldurur.

Neden burada kullanıldı? Saat, gün, ay gibi zaman bileşenleri süreklidir. Eğer saat 14:00 ise ve bir sonraki satır boşsa, onun da 14:00 (veya yakın bir zaman) olduğu varsayılabilir. Bu veriler kategorik/sıralı olduğu için en yakın geçmişteki bilgiyi kopyalamak güvenlidir.
"""

# Applying 'bfill' method on columns

data[['Temperature', 'Humidity']] = data[['Temperature', 'Humidity']].bfill()

"""Mantık: Eksik bir değeri, kendisinden bir sonraki geçerli değerle doldurur.

Neden burada kullanıldı? Sıcaklık ve nem gibi hava durumu verilerinde, bazen gelecekteki veriyi referans almak (özellikle veri setinin en başında boşluklar varsa) bir stratejidir. Ancak genellikle hava durumu için interpolate daha yaygındır; burada muhtemelen özel bir veri temizleme tercihi yapılmıştır.
"""

# Applying 'interpolate' method on columns

data['Demand'] = data['Demand'].interpolate(method = 'time')

"""Mantık: İki bilinen nokta arasına düz bir çizgi çeker gibi ara değerleri hesaplar. method='time' parametresi, değerleri doldururken satırların arasındaki zaman farkına (index'in datetime olması gerekir) dikkat eder.

Neden burada kullanıldı? "Demand" (Talep) genellikle ani sıçramalar yapmayan, belirli bir trend izleyen sayısal bir veridir. Örneğin; saat 10:00'da talep 100, saat 12:00'de 200 ise; interpolasyon saat 11:00'deki boşluğu otomatik olarak 150 yaparak doldurur.

"""

# Check for Missing Values

data.isnull().sum()

# Shape of dataframe

data.shape

data

# Create the 'Quarter' column at 5th index in the dataset
data.insert(5,"quarter",data.index.quarter)
data

# Check some basic information about the dataset

data.info()

# Convert the datatype from float to integer of columns

data[['hour', 'dayofweek', 'month','year', 'dayofyear']] = data[['hour', 'dayofweek', 'month','year', 'dayofyear']].astype(int)

# Check some basic information about the dataset

data.info()

data

# Create the 'Week of Year' column at 5th index in the dataset

data.insert(5, 'weekofyear', data.index.isocalendar().week.astype(int))
data

# Create a new column at 7th index to check the Weekend

data.insert(7, 'is_weekend', data.index.dayofweek.isin([5,6]))

data

#Convert the datatype from float to integer of the column

data['is_weekend'] = data['is_weekend'].astype(int)

data

# filtering the dataframe to get all records/rows where we have weekend

data[data['is_weekend'] == 1]

# import Holidays package

import holidays

# create a new column that will show holidays, otherwise NaN

data['Holidays'] = holidays.IN(years = data.year)

data

# using value_counts() to check the holidays with their count/occurance

data.Holidays.value_counts()

# deleting the 'Holidays' column from the dataframe

data = data.drop('Holidays', axis=1)

data

"""# Lagged Features: These are the past values of a time series data.

# Use - Past demand values are strong predictors. They can be used as input to predict future values.
"""

# Create a new column that will contain Demand from the same hour yesterday

data['Demand_lag_24hr'] = data['Demand'].shift(24)

# Create a new column that will contain Demand from the same hour last week

data['demand_lag_168hr'] = data['Demand'].shift(168) # 24x7 = 168 hours for weekly shift

# show top rows of the dataframe

data.head(50)

# using iloc function for the slicing of dataframe' rows

data.iloc[160:200]

# Create a new column that will contain Rolling Mean of the Demand in last 24 hours

data['demand_rolling_mean_24hr'] = data['Demand'].rolling(window=24).mean()

# Create a new column that will contain Rolling Standard Deviation of the Demand in last 24 hours

data['demand_rolling_std_24hr'] = data['Demand'].rolling(window=24).std()

# show top rows of the dataframe

data.head(27)

# Drop all Rows having null values

data = data.dropna()
data

# Plot raw demand over time

data['Demand'].plot(figsize =(15,6), title = "Electricity Demand Over Time")
plt.xlabel("Year")                          # naming for x-axis
plt.ylabel("Demand (in MW)")                # naming for y-axis

plt.show()

# Visualize demand by hour of day, using boxplot

plt.figure(figsize = (10,6))
sns.boxplot(data = data, x = 'hour', y = 'Demand')
plt.title("Demand by Hour of the day");

# Visualize demand by month, using boxplot

plt.figure(figsize=(10,6))
sns.boxplot(data = data, x = 'month', y = 'Demand')
plt.title("Demand by Month")
plt.show()

# Scatter plot of Demand vs. Temperature

plt.figure(figsize=(10,6))
sns.scatterplot(data = data, x = 'Temperature', y = 'Demand', alpha = 0.5)  #alpha - to adjust the tranparency of points
plt.title("Demand vs Temperature")
plt.show()

# Correlation Matrix and Heatmap

plt.figure(figsize=(12,8))
sns.heatmap(data.corr(), annot = True, fmt=".2f") # anoot=True : to show the numbers , fmt : to adjust decimals
plt.title("Correlation Matrix of Features")
plt.show()

# Defining Target Variable (Y)

Y = data.Demand                         # target variable / dependent variable

print(Y)           # Target variable

# Defining Features (X)

X = data.drop('Demand', axis=1)         # independent variables / features / predictors

X                    # Features

# Splitting the data into Training and Testing data

X_train = X.loc[ : '2023-12-31']                  # taking 80% of data as training data

X_train                                           # 80% of the training features data

Y_train = Y.loc[ : '2023-12-31' ]             # taking 80% of data as training data

Y_train                                       # 80% of the training target variable

X_test = X.loc[ '2024-01-01' : ]               # taking 20% of data as testing data

X_test                                         # 20% of the training features data

Y_test = Y.loc[ '2024-01-01' : ]                       # taking 20% of data as testing data

Y_test                                                 # 20% of the testing target variable

print(X_train.shape)
print(Y_train.shape)

print(X_test.shape)
print(Y_test.shape)

"""# XGBoost

XGBoost is a powerful algorithm for time-series forecasting, as it can handle non-linear data easily.

It can handle seasonality and trends in time-series data effectively.
"""

from xgboost import XGBRegressor     # from XGBoost library we are importing XGBRegressor class

# from sklearn library importing two fundamental metrics to evaluate the performance of the model
from sklearn.metrics import mean_squared_error, mean_absolute_error

# from model_selection module of scikit-learn's library, import TimeSeriesSplit class
# TimeSeriesSplit class performs appropriate cross-validation when dealing with time series data
from sklearn.model_selection import TimeSeriesSplit

"""Bu bölümde modelleme için gerekli araçlar yükleniyor:

XGBRegressor: XGBoost kütüphanesinden regresyon (sayısal tahmin) problemlerini çözmek için kullanılan ana sınıf.

mean_squared_error ve mean_absolute_error: Modelin tahmin başarısını ölçmek için kullanılan metrikler (Hata kareler ortalaması ve mutlak hata ortalaması).

TimeSeriesSplit: Zaman serisi verilerine özel bir çapraz doğrulama (cross-validation) yöntemidir. Verinin kronolojik sırasını bozmadan test ve eğitim setlerine ayrılmasını sağlar.
"""

# Initialize and train the model

model_xgb = XGBRegressor(n_estimators = 1000,
                         early_stopping_rounds = 50,
                         learning_rate = 0.01,
                         random_state = 42,
                         objective = 'reg:squarederror' )

"""model_xgb = XGBRegressor(...) satırı, modelin "beynini" yapılandırıyor:

n_estimators = 1000: Modelin toplamda oluşturabileceği maksimum ağaç (boosting turu) sayısıdır.

early_stopping_rounds = 50: Modelin aşırı öğrenmesini (overfitting) engellemek için kullanılır. Eğer doğrulama setindeki performans 50 tur boyunca iyileşmezse eğitimi durdurur.

learning_rate = 0.01: Her bir ağacın modele olan katkısını sınırlar. Küçük bir öğrenme oranı, modelin daha yavaş ama daha kararlı öğrenmesini sağlar.

random_state = 42: Kod her çalıştırıldığında aynı rastgele sonuçların üretilmesini sağlar (tekrarlanabilirlik).

objective = 'reg:squarederror': Modelin neyi minimize etmeye çalışacağını belirler. Burada amaç, tahmin edilen değer ile gerçek değer arasındaki kare farkını (hatayı) en aza indirmektir.

In short :

The XGBRegressor initialization creates a model that will train for up to 1000 boosting rounds (trees) but will stop early if performance on a validation set doesn't improve for 50 consecutive rounds.

Each tree's contribution is scaled down by a learning rate of 0.01 to prevent overfitting.

This model is designed to minimize the squared error for regression tasks.

3. Neden Zaman Serisinde XGBoost?

XGBoost şu avantajları sunar:

Doğrusal olmayan (non-linear) verileri kolayca işleyebilir.

Verideki mevsimsellik (seasonality) ve trendleri etkili bir şekilde yakalayabilir.
"""

# training the model

model_xgb.fit(X_train, Y_train, eval_set = [(X_train, Y_train), (X_test, Y_test)], verbose = False)

"""fit: Modeli eğitme komutudur. Model, X_train (girdi özellikleri) ve Y_train (hedef değerler) arasındaki ilişkiyi öğrenir.

eval_set: Eğitim sırasında modelin performansını hem eğitim hem de test setinde izlemesini sağlar. Bu, modelin "ezberleyip ezberlemediğini" (overfitting) kontrol etmek için kritiktir.

verbose = False: Eğitim sırasındaki her bir adımın (turun) çıktılarını ekrana yazdırmaz, süreci sessizce yürütür.
"""

# Make predictions

predictions_xgb = model_xgb.predict(X_test)

# Evaluating the model

rmse_xgb = np.sqrt(mean_squared_error(Y_test, predictions_xgb))

mae_xgb = mean_absolute_error(Y_test, predictions_xgb )

print('XGBoost RMSE:',  rmse_xgb)
print('XGBoost MAE:' ,  mae_xgb)

"""Model eğitildikten sonra, görmediği veriler (X_test) üzerinde ne kadar başarılı olduğu ölçülür:

predict(X_test): Eğitilen modeli kullanarak test verileri için tahminler üretir.

RMSE (Root Mean Squared Error): Hataların karesinin ortalamasının kareköküdür. Büyük hatalara daha fazla ceza keser.

MAE (Mean Absolute Error): Tahminler ile gerçek değerler arasındaki mutlak farkın ortalamasıdır.

Sonuçlar: Görseldeki verilere göre modelin RMSE değeri ~174.82, MAE değeri ise ~123.47 çıkmıştır. Bu değerler ne kadar düşükse model o kadar başarılıdır.
"""

# Visulaize the Predictions

plt.figure(figsize = (15,6))
plt.plot(Y_test.index, Y_test, label = 'Actual Demand', color = 'Blue')
plt.plot(Y_test.index, predictions_xgb, label = 'Predicted Demand', color = 'Red', linestyle='--')
plt.title('XGBoost Electricity Demand Prediction')
plt.xlabel('Date')
plt.ylabel('Demand')
plt.legend()

plt.show()

"""Mavi Çizgi: Gerçek elektrik talebi (Actual Demand).

Kırmızı Kesikli Çizgi: Modelin tahmini (Predicted Demand).

Grafiğe bakıldığında kırmızı çizgilerin mavi çizgileri çok yakından takip ettiği, yani modelin genel trendi ve mevsimselliği başarıyla yakaladığı görülmektedir.
"""

# save the model

import joblib

joblib.dump(model_xgb, 'electricity_xgb_prediction_model.pkl')

# load and Use:

loaded_model = joblib.load('electricity_xgb_prediction_model.pkl')

# future_predictions = loaded_model.predict(X_future)

loaded_model

"""Modeli her seferinde yeniden eğitmek yerine diske kaydedip ihtiyacınız olduğunda kullanabilirsiniz:

joblib.dump: Eğitilmiş model_xgb nesnesini .pkl uzantılı bir dosya olarak kaydeder.

joblib.load: Kaydedilen bu dosyayı geri yükler. Böylece loaded_model.predict(X_future) diyerek yeni, gelecekteki veriler için anında tahmin alabilirsiniz.
"""